#!/bin/sh

#eval $(dpkg-architecture)
export DEB_HOST_MULTIARCH=arm-linux-gnueabihf

rm -f "/usr/lib/${DEB_HOST_MULTIARCH}/libGL.so.1"
ln -s /usr/lib/gl4es/libGL.so.1 "/usr/lib/${DEB_HOST_MULTIARCH}/libGL.so.1"

#DEBHELPER#
